osx_image: xcode11.3
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI

rvm: 2.6.4
before_install:
  - gem update cocoapods
  - gem install bundler
  - bundle install
  - gem install xcpretty

script: ./test.sh
